indices:
- name: 上证指数
  code: '000001'
  market: sh
  type: index
- name: 深证成指
  code: '399001'
  market: sz
  type: index
- name: 创业板指
  code: '399006'
  market: sz
  type: index
- name: 沪深300
  code: '000300'
  market: sh
  type: index
- name: 科创50
  code: 000688
  market: sh
  type: index
- name: 恒生指数
  code: HSI
  market: hk
  type: index
sectors:
- name: 农林牧渔
  code: '801010'
  market: ''
  type: sector
- name: 采掘
  code: '801020'
  market: ''
  type: sector
- name: 白酒板块
  code: '801110'
  market: sh
  type: sector
stocks:
- name: 贵州茅台
  code: '600519'
  market: sh
  type: stock
  notes: 长期投资
  industry: 白酒
  strategy: 周线超卖均值回归买入(买) + 周线超买均值回归卖出(卖)
  buy_strategy: 周线超卖均值回归买入
  sell_strategy: 周线超买均值回归卖出
- name: 比亚迪
  code: 002594
  market: sz
  type: stock
  industry: 汽车整车
  strategy: 长线4421极限买入(买) + 长线泡沫卖出(卖)
  buy_strategy: 长线4421极限买入
  sell_strategy: 长线泡沫卖出
- name: 宁德时代
  code: '300750'
  market: sz
  type: stock
  industry: 电气设备
  strategy: 防御慢牛回调买入(买) + 防御慢牛顶部卖出(卖)
  buy_strategy: 防御慢牛回调买入
  sell_strategy: 防御慢牛顶部卖出
- name: 阿里巴巴
  code: 09988
  market: hk
  type: stock
  notes: 这个坑
  strategy: RSI超卖反弹买入(买) + RSI超买卖出(卖)
  buy_strategy: RSI超卖反弹买入
  sell_strategy: RSI超买卖出
- name: 上海机场
  code: '600009'
  market: sh
  type: stock
  industry: 机场
  strategy: 布林带下轨买入(买) + 布林带上轨卖出(卖)
  buy_strategy: 布林带下轨买入
  sell_strategy: 布林带上轨卖出
- name: 索菲亚
  code: '002572'
  market: sz
  type: stock
  industry: 家居用品
  strategy: 中线超跌买入(买) + 中线超跌卖出(卖)
  buy_strategy: 中线超跌买入
  sell_strategy: 中线超跌卖出
- name: 优必选
  code: 09880
  market: hk
  type: stock
  strategy: 短线突破买入(买) + 短线趋势卖出(卖)
  buy_strategy: 短线突破买入
  sell_strategy: 短线趋势卖出
- name: 快手-W
  code: '01024'
  market: hk
  type: stock
  strategy: 混搭：短线突破买入买×成长股强势动量卖出卖
  buy_strategy: 短线突破买入
  sell_strategy: 成长股强势动量卖出
- name: 特海国际
  code: 09658
  market: hk
  type: stock
  strategy: 长线4421极限买入(买) + 长线泡沫卖出(卖)
  buy_strategy: 长线4421极限买入
  sell_strategy: 长线泡沫卖出
- name: 阳光电源
  code: '300274'
  market: sz
  type: stock
  industry: 电气设备
  strategy: 混搭：长线4421极限买入买×RSI超买卖出卖
  buy_strategy: 长线4421极限买入
  sell_strategy: RSI超买卖出
- name: 德赛西威
  code: 002920
  market: sz
  type: stock
  industry: 汽车配件
  strategy: 中线超跌买入(买) + 中线超跌卖出(卖)
  buy_strategy: 中线超跌买入
  sell_strategy: 中线超跌卖出
- name: 万华化学
  code: '600309'
  market: sh
  type: stock
  industry: 化工原料
  strategy: RSI超卖反弹买入(买) + RSI超买卖出(卖)
  buy_strategy: RSI超卖反弹买入
  sell_strategy: RSI超买卖出
- name: 波司登
  code: 03998
  market: hk
  type: stock
  strategy: 短线突破买入(买) + 短线趋势卖出(卖)
  buy_strategy: 短线突破买入
  sell_strategy: 短线趋势卖出
- name: 国盾量子
  code: '688027'
  market: sh
  type: stock
  industry: 通信设备
  strategy: 防御慢牛回调买入(买) + 防御慢牛顶部卖出(卖)
  buy_strategy: 防御慢牛回调买入
  sell_strategy: 防御慢牛顶部卖出
- name: 沪电股份
  code: '002463'
  market: sz
  type: stock
  industry: 元器件
  strategy: 中线超跌买入(买) + 中线超跌卖出(卖)
  buy_strategy: 中线超跌买入
  sell_strategy: 中线超跌卖出
- name: 英维克
  code: 002837
  market: sz
  type: stock
  industry: 专用机械
  strategy: 中线超跌买入(买) + 中线超跌卖出(卖)
  buy_strategy: 中线超跌买入
  sell_strategy: 中线超跌卖出
- name: 长江电力
  code: '600900'
  market: sh
  type: stock
  industry: 水力发电
  strategy: 布林带下轨买入(买) + 布林带上轨卖出(卖)
  buy_strategy: 布林带下轨买入
  sell_strategy: 布林带上轨卖出
- name: 华阳集团
  code: 002906
  market: sz
  type: stock
  industry: 汽车配件
  strategy: 混搭：布林带下轨买入买×KDJ超买卖出卖
  buy_strategy: 布林带下轨买入
  sell_strategy: KDJ超买卖出
- name: 腾讯控股
  code: '00700'
  market: hk
  type: stock
  strategy: 长线4421极限买入(买) + 长线泡沫卖出(卖)
  buy_strategy: 长线4421极限买入
  sell_strategy: 长线泡沫卖出
- name: 拓普集团
  code: '601689'
  market: sh
  type: stock
  industry: 汽车配件
  strategy: 防御慢牛回调买入(买) + 防御慢牛顶部卖出(卖)
  buy_strategy: 防御慢牛回调买入
  sell_strategy: 防御慢牛顶部卖出
- name: 中芯国际
  code: '688981'
  market: sh
  type: stock
  industry: 半导体
  strategy: 混搭：RSI超卖反弹买入买×布林带上轨卖出卖
  buy_strategy: RSI超卖反弹买入
  sell_strategy: 布林带上轨卖出
- name: 北方华创
  code: '002371'
  market: sz
  type: stock
  industry: 半导体
  strategy: 混搭：长线4421极限买入买×KDJ超买卖出卖
  buy_strategy: 长线4421极限买入
  sell_strategy: KDJ超买卖出
- name: 五粮液
  code: 000858
  market: sz
  type: stock
  industry: 白酒
  strategy: 中线超跌买入(买) + 中线超跌卖出(卖)
  buy_strategy: 中线超跌买入
  sell_strategy: 中线超跌卖出
- name: 颐海国际
  code: 01579
  market: hk
  type: stock
  strategy: 短线突破买入(买) + 短线趋势卖出(卖)
  buy_strategy: 短线突破买入
  sell_strategy: 短线趋势卖出
- name: 小米集团-W
  code: 01810
  market: hk
  type: stock
  strategy: 长线4421极限买入(买) + 长线泡沫卖出(卖)
  buy_strategy: 长线4421极限买入
  sell_strategy: 长线泡沫卖出
- name: 华勤技术
  code: '603296'
  market: sh
  type: stock
  industry: 元器件
  strategy: 价值动量共振买入(买) + 价值动量共振卖出(卖)
  buy_strategy: 价值动量共振买入
  sell_strategy: 价值动量共振卖出
- name: 海底捞
  code: 06862
  market: hk
  type: stock
  strategy: 布林带下轨买入(买) + 布林带上轨卖出(卖)
  buy_strategy: 布林带下轨买入
  sell_strategy: 布林带上轨卖出
- name: 首华燃气
  code: '300483'
  market: sz
  type: stock
  industry: 石油开采
  strategy: 混搭：长线4421极限买入买×RSI超买卖出卖
  buy_strategy: 长线4421极限买入
  sell_strategy: RSI超买卖出
- name: '159632'
  code: '159632'
  market: sz
  type: etf
- name: 泡泡玛特
  code: 09992
  market: hk
  type: stock
  strategy: 长线4421极限买入(买) + 长线泡沫卖出(卖)
  buy_strategy: 长线4421极限买入
  sell_strategy: 长线泡沫卖出
