indices:
- name: 上证指数
  code: '000001'
  market: sh
  type: index
- name: 深证成指
  code: '399001'
  market: sz
  type: index
- name: 创业板指
  code: '399006'
  market: sz
  type: index
- name: 沪深300
  code: '000300'
  market: sh
  type: index
- name: 科创50
  code: 000688
  market: sh
  type: index
- name: 恒生指数
  code: HSI
  market: hk
  type: index
sectors:
- name: 农林牧渔
  code: '801010'
  market: ''
  type: sector
- name: 采掘
  code: '801020'
  market: ''
  type: sector
- name: 白酒板块
  code: '801110'
  market: sh
  type: sector
stocks:
- name: 贵州茅台
  code: '600519'
  market: sh
  type: stock
  notes: 长期投资
  industry: 白酒
  strategy: MACD策略
  buy_strategy: MACD策略
  sell_strategy: MACD策略
- name: 中国平安
  code: '601318'
  market: sh
  type: stock
  industry: 保险
  strategy: RSI策略
  buy_strategy: RSI策略
  sell_strategy: RSI策略
- name: 比亚迪
  code: 002594
  market: sz
  type: stock
  industry: 汽车整车
  strategy: 布林带下轨买入
  buy_strategy: 布林带下轨买入
  sell_strategy: 布林带上轨卖出
- name: 宁德时代
  code: '300750'
  market: sz
  type: stock
  industry: 电气设备
- name: 阿里巴巴
  code: 09988
  market: hk
  type: stock
  notes: 这个坑
- name: 洋河股份
  code: '002304'
  market: sz
  type: stock
  industry: 白酒
- name: 泸州老窖
  code: 000568
  market: sz
  type: stock
  industry: 白酒
- name: 上海机场
  code: '600009'
  market: sh
  type: stock
  industry: 机场
- name: 索菲亚
  code: '002572'
  market: sz
  type: stock
  industry: 家居用品
  strategy: 中线2超跌
  buy_strategy: 中线2超跌
  sell_strategy: 中线超跌卖出
